/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NfButton: typeof import('@94ai/nf-button/lib/nf-button.esm-bundler.js')['default']
    NfDatePicker: typeof import('@94ai/nf-date-picker/lib/nf-date-picker.esm-bundler.js')['default']
    NfDoubleHalfYear: typeof import('@94ai/nf-double-half-year/lib/nf-double-half-year.esm-bundler.js')['default']
    NfDoubleQuarter: typeof import('@94ai/nf-double-quarter/lib/nf-double-quarter.esm-bundler.js')['default']
    NfDoubleWeek: typeof import('@94ai/nf-double-week/lib/nf-double-week.esm-bundler.js')['default']
    NfDoubleYear: typeof import('@94ai/nf-double-year/lib/nf-double-year.esm-bundler.js')['default']
    NfDrawer: typeof import('@94ai/nf-drawer/lib/nf-drawer.esm-bundler.js')['default']
    NfEmpty: typeof import('@94ai/nf-empty/lib/nf-empty.esm-bundler.js')['default']
    NfForm: typeof import('@94ai/nf-form/lib/nf-form.esm-bundler.js')['default']
    NfFormItem: typeof import('@94ai/nf-form-item/lib/nf-form-item.esm-bundler.js')['default']
    NfHalfYearPicker: typeof import('@94ai/nf-half-year-picker/lib/nf-half-year-picker.esm-bundler.js')['default']
    NfInput: typeof import('@94ai/nf-input/lib/nf-input.esm-bundler.js')['default']
    NfLazySelect: typeof import('@94ai/nf-lazy-select/lib/nf-lazy-select.esm-bundler.js')['default']
    NfQuarterPicker: typeof import('@94ai/nf-quarter-picker/lib/nf-quarter-picker.esm-bundler.js')['default']
    NfSearchForm: typeof import('@94ai/nf-search-form/lib/nf-search-form.esm-bundler.js')['default']
    NfTable: typeof import('@94ai/nf-table/lib/nf-table.esm-bundler.js')['default']
    NfTag: typeof import('@94ai/nf-tag/lib/nf-tag.esm-bundler.js')['default']
    NfTimezonePicker: typeof import('@94ai/nf-timezone-picker/lib/nf-timezone-picker.esm-bundler.js')['default']
    NfTransferSelect: typeof import('@94ai/nf-transfer-select/lib/nf-transfer-select.esm-bundler.js')['default']
    NfVirtualSelect: typeof import('@94ai/nf-virtual-select/lib/nf-virtual-select.esm-bundler.js')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
